language: node_js

node_js:
  - 6

before_script:
  - npm build
  - npm start &
  - npm run update-webdriver

script:
  - xvfb-run npm test

deploy:
  provider: script
  script: deploy.sh
  on:
    repo: mdb/testing-with-xvfb
    branch: master
